[package]
name = "title-suffixer-action"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error = "0.1.9"
octocrab = "0.17.0"
regex = "1.7.0"
tokio = { version = "1.23.0", features = ["full"] }
